### ISSUE TITLE
chore: basic todo list 

### ISSUE THREAD

**Issue by mackcoding** [mackcoding/WhoisNET#1]
*TcpHandler.cs*
- [x] `WriteAsync` checks if _stream is null and writes an exception. Determine if this is necessary, repeat for other instances of WriteAsync.
- [x] Whenever `Debug.WriteException` is called, a string is created, and the exception is called. Reduce this to one call.
- [x] `WriteAsync` needs an overhaul, clean up the code and reduce it if possible

*RegExpressions.cs*
- [x] Determine if we need `GetRir()`
- [ ]  Get rid of entire class and write a proper parser, see issue #3 

*Utilities.cs*
- [x] Move a portion of `GetTld` to the `Network` namespace, and write a similar class as `TcpHandler.cs` for `HttpClient`.

*Whois.cs*
- [ ] Write a parser for lookups. See issue #3 
- [x] Determine if we really need `followRefer`
- [x] In QueryAsync, there is a `server.Contains` call for arin.net. Move this logic to its own method for future expansion
- [x] Determine why `rwhois.mediacomcc.com` leads to a dead server, and find a solution for this situation
- [x] Rewrite/cleanup `FindQueryAsync()` method. See issue #2
- [x] Move `whois.iana.org` to a const (and others)
- [x] Accept a dictionary of options.
