### ISSUE TITLE
chore: update meta information for projects

### ISSUE THREAD

**Issue by mackcoding** [mackcoding/WhoisNET#14]
Currently the assembly is outputted as Whois.Client.exe, rename it so it outputs "whois.exe" and apply other optimizations such as:

- [x] Assembly Name: whois
- [x] Generate a file containing API documentation
- [x] Publish trimmed
- [x] Publish Native AOT (might hold off on this)
- [x] Internal compiler error reporting: never send
- [x] Fill out Authors, Company, Product, Description, Copyright, Project URL, Icon, Readme, Repository URL, Tags, 
- [x] Package license
